function ds_rdm = rsa_table2ds(rdmTable, tolatex)
% ds_rdm = rsa_table2ds(rdmTable, tolatex)
%
% Convert MVPA table (got from fs_cosmo_cvdecode()) to RDM ds. [The
% accuracy will be convert to 1-accuracy.]
%
% Inputs:
%     rdmTable     <table> MVPA table generated by fs_cosmo_cvcode().
%     tolatex      <boo> whether update condition names to latex. Default
%                   to 1.
%
% Output:
%     ds_rdm       <struct> RDM ds.
%
% Created by Haiyang Jin (2022-Aug-25)

if nargin < 1
    fprintf('Usage: ds_rdm = rsa_table2ds(rdmTable, tolatex);\n');
    return
end

if ~exist('tolatex', 'var') || isempty(tolatex)
    tolatex = 1;
end

%% Reformat the information
% get average for each subject/session
subjGrp = grpstats(rdmTable, ["Label", "SessCode", "ClassifyPair"], ...
    "mean", "DataVars","ACC");

% number of labels
labelList = unique(subjGrp.Label);
nLabel = numel(labelList);

% number of subjects
subjList = unique(subjGrp.SessCode);
nSubj = numel(subjList);

% conditions
condPairs = unique(subjGrp.ClassifyPair, 'stable');
% convert condition pairs the condition list
condcells = cellfun(@(x) strsplit(x, '-'), condPairs, 'uni', false);
condList = unique(horzcat(condcells{:}), 'stable')';

% create empty samples
samples = nan(nchoosek(length(condList), 2), nLabel, nSubj);

% save the samples
for iLabel = 1:nLabel

    thisLabel = labelList(iLabel);
    thisTable = subjGrp(strcmp(subjGrp.Label, thisLabel), :);

    for iSubj = 1:nSubj

        thisSubj = subjList(iSubj);
        theT = thisTable(strcmp(thisTable.SessCode, thisSubj), :);

        if isempty(theT)
            continue
        end

        assert(isequal(condPairs, theT.ClassifyPair), ['The condition ' ...
            'pairs do not seem to match for different conditions.'])

        samples(:, iLabel, iSubj) = 1-theT.mean_ACC;

    end %iSubj
end %iLabel

% adapt condition names to Latex
if tolatex
    condList = cellfun(@(x) strrep(x, '_', '\_'), condList, 'uni', false);
end

%% Save ds_rdm
ds_rdm = rsa_ds(samples, 'condlist', condList, ...
    'labellist', labelList, 'subjlist', subjList);

end