function fscmd = fm_cmd2txt(outFn, outPath, varargin)
% fscmd = fm_cmd2txt([outFn='fscmd.txt', outPath], varargin)
%
% This function saves the FreeSurfer commands (fscmd) generated by some
% funcitons (e.g., fs_mkanalysis, fs_mkcontrast, fs_selxavg3) as a *.txt
% file [only the first column of fscmd will be saved].
%
% Inputs:
%    outFn        <string> the filename of the output file. If path is
%                  included in outFn, outPath will be ignored. Default is
%                  'fscmd.txt'.
%    outPath      <string> the folder where outFn will be saved. Default is
%                  a folder called 'fscmd' in the Desktop folder.
%    varargin     all the to-be-saved fscmd.
%
% Output:
%    fscmd        <cell string> all fscmd in varargin.
%
% Example:
% fscmd = fm_cmd2txt('fscmd.txt', '~/Desktop/fscmd', fscmd_ana, fscmd_con, fscmd_avg);
%
% Created by Haiyang Jin (18-Apr-2020)

if ~exist('outFn', 'var') || isempty(outFn)
    outFn = 'fscmd.txt';
end

if ~isempty(fileparts(outFn))
    % if path is included in outFn
    outFilename = outFn;
    outPath = fileparts(outFn);
else
    % create outFn if necessary
    if ~exist('outPath', 'var') || isempty(outPath)
        outPath = fullfile('~', 'Desktop', 'fscmd');
    end
    outFilename = fullfile(outPath, outFn);
end

% make directory if it does not exist
if ~exist(outPath, 'dir'); mkdir(outPath); end

% combine all fscmds
fscmd = vertcat(varargin{:});

% save the first column of fscmd
fm_mkfile(outFilename, fscmd(:, 1));

end