function fs_hcp_runlistfile(funcPath, strPattern, locString)
% fs_hcp_runlistfile(funcPath, strPattern, locString)
%
% This function reads the run_info.txt generated by fs_hcp_prepro and 
% creates the run list files.
% 
% If there are more than one type of task names (i.e., the folder names 
% without the run number at the end). The task name containing
% locString will be regarded as the localizer runs.
%
% if there is only one task name, the folder name (including the run
% number) containing locString will be regarded as the localizer runs.
%
% Input:
%    funcPath       <string> path to the functional data folder. Default is
%                    "$FUNCTIONALS_DIR". 
%    strPattern     <string> the string pattern for session names. It
%                    will be used to identify all the sessions. E.g., it
%                    can be "Face*" (without quotes). Default is the string
%                    obtained from hcp_projname.
%    locString      <string> or <cell of string> folder names containing
%                   locString will be regarded as loc (localizer) runs.
% Output:
%    run list files in the bold/ folder
%
% Created by Haiyang Jin (2020-01-06)

if ~exist('funcPath', 'var')
    funcPath = '';
end

if ~exist('strPattern', 'var') || isempty(strPattern)
    strPattern = hcp_projname;
end
[funcPath, sessList] = fs_funcdir(funcPath, [strPattern '*']);

if ~exist('locString', 'var') || isempty(locString)
    locString = 'loc';
end

% create run files for each session separately
cellfun(@(x) runlistfile(x, locString), fullfile(funcPath, sessList, 'bold'), 'uni', false);

end

function runlistfile(boldPath, locString)

% load run_info.txt
runInfo = readtable(fullfile(boldPath, 'run_info.txt'), 'Delimiter', ',',...
    'Format','%s%s');

%% find unique task names and numbers
% the unique strings of run names (as the task name)
runNums = cellfun(@(x) regexp(x, '\d+', 'match'), runInfo.RunName);
[taskNames, ~, groupNum] = unique(cellfun(@(x, y) erase(x, y),...
    runInfo.RunName, runNums, 'uni', false));

% classify runs into different types (loc and main(s))
nTask = numel(taskNames);

if nTask > 1 % when there are more than one types of task names
    
    mainCell = cell(nTask-1, 1);
    mainNum = 0;
    
    for iTask = 1:nTask
        
        thisTaskName = taskNames{iTask};
        if contains(thisTaskName, locString, 'IgnoreCase', true)
            % runs are treated as loc runs if the run names contains 'loc'
            locList = groupNum == iTask;
        else
            % other runs are treated as main runs
            mainNum = mainNum + 1;
            mainCell(mainNum, 1) = {groupNum == iTask};
        end
        
    end
    
elseif nTask == 1 % when there is only one task name
    
    mainNum = 1;
    locList = contains(runInfo.RunName, locString);
    
    mainCell{1, 1} = ~locList;
    
end

%% Create run list files
% backup directory
wdBackup = pwd;
cd(boldPath);

% loc runs
createrunlistfile('run_loc', runInfo, locList);

% main runs
if mainNum == 1 % if there is only one task (main) run
    
    createrunlistfile('run_main', runInfo, mainCell{1, 1});
    
elseif mainNum > 1 % if there are more than one tasks
    
    arrayfun(@(x) createrunlistfile(sprintf('task%d_run_main', x), ...
        runInfo, mainCell{x, 1}), 1:mainNum, 'uni', false);
end

% change back to the backup working directory
cd(wdBackup);

end


function createrunlistfile(runType, runInfo, logicalList) 

% create run list files for each run separately
arrayfun(@(x,y) fm_createfile([runType num2str(x) '.txt'],...
    y), 1:sum(logicalList), runInfo{logicalList, 'RunCode'}', 'uni', false);

% create run list file for all runs together
fm_createfile([runType '.txt'], runInfo{logicalList, 'RunCode'});

end
