function anaInfo = fs_readanainfo(anainfofn, sessCode)
% anaInfo = fs_readanainfo(anainfofn, sessCode)
%
% Reads the analysis.info file, which is generated by mkanalysis-sess in
% FreeSurfer.
%
% Input:
%    anainfofn       <str> path to the 'analysis.info' file. Default is
%                     pwd.
%    sessCode        <str> session code in $FUNCTIONALS_DIR.
%
% Output:
%    anaInfo         <struct> information read from analysis.info.
%
% Created by Haiyang Jin (2022-Jan-06)

if ~exist('anainfofn', 'var') || isempty(anainfofn)
    anainfofn = pwd;
end

path = fileparts(anainfofn);

if isempty(path)
    % add path to runFn if sessCode is not empty
    if ~exist('sessCode', 'var') || isempty(sessCode)
        anainfofilename = fullfile(getenv('FUNCTIONALS_DIR'), anainfofn);
        warning('Analysis information is obtained from the folder in $FUNCTIONALS_DIR.');
    else
        anainfofilename = fullfile(getenv('FUNCTIONALS_DIR'), sessCode, 'bold', anainfofn);
    end
else
    anainfofilename = anainfofn;
end

% the filename should be 'analysis.info'
if ~endsWith(anainfofilename, 'analysis.info')
    anainfofilename = fullfile(anainfofilename, 'analysis.info');
end

% scan the strings
[fid, mes] = fopen(anainfofilename);
if fid == -1 % sanity check
    warning(mes); 
    anaInfo = [];
    return;
end
% read each row separately
contentC = textscan(fid, '%s', 'delimiter', '\n', 'whitespace', '', ...
    'CommentStyle', '#');
fclose(fid);

contents = cellfun(@(x) split(x, ' '), contentC{1}, 'uni', false);
contents(cellfun(@length, contents)<2) = [];

% save the data in struct
anaInfo = struct;
for i = 1:length(contents)

    thisrow = contents{i};

    tmp_value = str2double(thisrow{2});

    if length(thisrow) > 2
        anaInfo.(thisrow{1}) = sprintf('%s ', thisrow{2:end});
    elseif isnan(tmp_value)
        anaInfo.(thisrow{1}) = thisrow{2};
    else
        % convert to double if possible
        anaInfo.(thisrow{1}) = tmp_value;
    end
end

end