function anaInfo = fs_readanainfo(anainfofn, sessCode)
% anaInfo = fs_readanainfo(anainfofn, sessCode)
%
% Reads the analysis.info file, which is generated by mkanalysis-sess in
% FreeSurfer.
%
% Input:
%    anainfofn       <str> path to the 'analysis.info' file. Default is
%                     pwd.
%    sessCode        <str> session code in $FUNCTIONALS_DIR.
%
% Output:
%    anaInfo         <struct> information read from analysis.info.
%
% Created by Haiyang Jin (2022-Jan-06)

if ~exist('anainfofn', 'var') || isempty(anainfofn)
    anainfofn = pwd;
end

path = fileparts(anainfofn);

if isempty(path)
    % add path to runFn if sessCode is not empty
    if ~exist('sessCode', 'var') || isempty(sessCode)
        error('''sessCode'' is missing.');
    else
        anainfofilename = fullfile(getenv('FUNCTIONALS_DIR'), sessCode, 'bold', anainfofn);
    end
else
    anainfofilename = anainfofn;
end

% the filename should be 'analysis.info'
if ~endsWith(anainfofilename, 'analysis.info')
    anainfofilename = fullfile(anainfofilename, 'analysis.info');
end

% scan the strings
[fid, mes] = fopen(anainfofilename);
if fid == -1 % sanity check
    warning(mes); 
    anaInfo = [];
    return;
end
dataCell = textscan(fid, '%s%s', 'CommentStyle', '#');
fclose(fid);

fns = dataCell{1,1};
values = dataCell{1,2};

% only save the data for the first 31 rows (which should provide sufficient
% information)
anaInfo = struct;
for i = 1:31

    tmp_value = str2double(values{i});

    if isnan(tmp_value)
        anaInfo.(fns{i}) = values{i};
    else
        % convert to double if possible
        anaInfo.(fns{i}) = tmp_value;
    end
end

end