function anaInfo = fs_readanainfo(anainfofn)
% anaInfo = fs_readanainfo(anainfofn)
%
% Reads the analysis.info file, which is generated by mkanalysis-sess in
% FreeSurfer.
%
% Input:
%    anainfofn       <str> path to the 'analysis.info' file. Default is
%                     pwd.
%
% Output:
%    anaInfo         <struct> information read from analysis.info.
%
% Created by Haiyang Jin (2022-Jan-06)

if ~exist('anainfofn', 'var') || isempty(anainfofn)
    anainfofn = pwd;
end

% the filename should be 'analysis.info'
if ~endsWith(anainfofn, 'analysis.info')
    anainfofn = fullfile(anainfofn, 'analysis.info');
end

% scan the strings
[fid, mes] = fopen(anainfofn);
assert(fid ~= -1, mes); % sanity check
dataCell = textscan(fid, '%s%s', 'CommentStyle', '#');
fclose(fid);

fns = dataCell{1,1};
values = dataCell{1,2};

% only save the data for the first 30 rows (which should provide sufficient
% information)
anaInfo = struct;
for i = 1:30
    anaInfo.(fns{i}) = values{i};
end

end